### ISSUE TITLE
encoder arp mode idx out of range error

### ISSUE THREAD

**Issue by derrickthomin** [derrickthomin/DJBB-Loopster-2.0#16]
Traceback (most recent call last):
  File "<stdin>", line 41, in <module>
  File "inputs.py", line 387, in process_inputs_fast
  File "arp.py", line 47, in get_next_arp_note
IndexError: index out of range

got this when holding two chorded up pads and turning encoder. Then stopping and trying to do it again.

**Comment by derrickthomin** [comment]
fixed
